package com.davita.questionnaire.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.apache.catalina.User;

import javax.persistence.*;

@Entity
@ApiModel( value = "Address", description = "Address description")
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "Street name", dataType = "String")
    private String street;
    @ApiModelProperty(notes = "City name", dataType = "String")
    private String city;
    @ApiModelProperty(notes = "State name", dataType = "String")
    private String state;
    @ApiModelProperty(notes = "Zip code", dataType = "String")
    private String zip;

    @OneToOne(fetch = FetchType.EAGER, mappedBy = "address")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Person person;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }
}
