package com.davita.questionnaire.model;

import com.davita.questionnaire.util.JpaJsonConverter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;

@Entity
@ApiModel( value = "Form", description = "Form definition")
public class Form {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "Form name", dataType = "String")
    private String name;
    @Column(columnDefinition = "text")
    @Convert(converter = JpaJsonConverter.class)
    private ArrayList<FormSection> sections;

    public Form(Integer id, String name, ArrayList<FormSection> sections) {
        this.id = id;
        this.name = name;
        this.sections = sections;
    }

    public Form() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArrayList<FormSection> getSections() {
        return sections;
    }

    public void setSections(ArrayList<FormSection> sections) {
        this.sections = sections;
    }
}
