package com.davita.questionnaire.model;

import com.davita.questionnaire.util.JpaJsonConverter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;

@Entity
@Getter
@Setter
@ApiModel( value = "Form", description = "Form definition")
public class Form {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "Form name", dataType = "String")
    private String name;
    @Column(columnDefinition = "text")
    @Convert(converter = JpaJsonConverter.class)
    private ArrayList<FormSection> sections;

    public Form(Integer id, String name, ArrayList<FormSection> sections) {
        this.id = id;
        this.name = name;
        this.sections = sections;
    }

    public Form() {
    }
}
