package com.davita.questionnaire.model;

import com.davita.questionnaire.util.JpaJsonConverter;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ApiModel( value = "Form", description = "Form definition")
public class Form {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "Form name", dataType = "String")
    private String name;

    @Column(columnDefinition = "text")
    @Convert(converter = JpaJsonConverter.class)
    @ApiModelProperty(notes = "Form sections", dataType = "ArrayList<FormSection>")
    private ArrayList<FormSection> sections;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "form")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private List<Questionnaire> questionnaires;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "form")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private List<Submission> submissions;
}
