package com.davita.questionnaire.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Entity
@Getter
@Setter
@ApiModel( value = "Person", description = "Person description")
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "First name", dataType = "String")
    private String firstName;
    @ApiModelProperty(notes = "Middle name", dataType = "String")
    private String middleName;
    @ApiModelProperty(notes = "Last name", dataType = "String")
    private String lastName;
    @ApiModelProperty(notes = "Suffix", dataType = "String")
    private String suffix;
    @ApiModelProperty(notes = "Ssn", dataType = "String")
    private String ssn;
    @ApiModelProperty(notes = "Birth date", dataType = "String")
    private String birthDate;
    @ApiModelProperty(notes = "Birth place", dataType = "String")
    private String birthPlace;
    @ApiModelProperty(notes = "Birth country", dataType = "String")
    private String birthCountry;

    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @ApiModelProperty(notes = "Address", dataType = "Address")
    private Address address;

}
