package com.davita.questionnaire.model;

import com.davita.questionnaire.enums.QuestionnaireStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(uniqueConstraints = {
        @UniqueConstraint(columnNames = {"person_id", "form_id"})
})
@ApiModel( value = "Questionnaire", description = "Person / Form / Submission relation")
public class Questionnaire {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @Enumerated(EnumType.STRING)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private QuestionnaireStatus status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id")
    private Person person;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "form_id")
    private Form form;

    public Questionnaire(Integer id, QuestionnaireStatus status, Person person, Form form) {
        this.id = id;
        this.status = status;
        this.person = person;
        this.form = form;
    }

    public Questionnaire() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public QuestionnaireStatus getStatus() {
        return status;
    }

    public void setStatus(QuestionnaireStatus status) {
        this.status = status;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Form getForm() {
        return form;
    }

    public void setForm(Form form) {
        this.form = form;
    }
}
