package com.davita.questionnaire.model;

import com.davita.questionnaire.util.JpaJsonConverter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;

@Entity
@Getter
@Setter
@ApiModel( value = "Submission", description = "Form answers")
public class Submission {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "submit date", dataType = "String")
    private String submitDate;

    @Column(columnDefinition = "text")
    @Convert(converter = JpaJsonConverter.class)
    @ApiModelProperty(notes = "Form answers", dataType = "ArrayList<Answer>")
    private ArrayList<Answer> answers;

    @ManyToOne(fetch = FetchType.LAZY)
    private Questionnaire questionnaire;

    public Submission(Integer id, ArrayList<Answer> answers, Questionnaire questionnaire) {
        this.id = id;
        this.answers = answers;
        this.questionnaire = questionnaire;
    }

    public Submission() {
    }
}
