package com.davita.questionnaire.model;

import com.davita.questionnaire.util.JpaJsonConverter;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.ArrayList;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ApiModel( value = "Submission", description = "Form answers")
public class Submission {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "Autogenerated id", dataType = "Integer")
    private Integer id;
    @ApiModelProperty(notes = "submit date", dataType = "String")
    @NotNull
    private String submitDate;

    @Column(columnDefinition = "text")
    @Convert(converter = JpaJsonConverter.class)
    @ApiModelProperty(notes = "Form answers", dataType = "ArrayList<Answer>")
    private ArrayList<Answer> answers;

    @ManyToOne(fetch = FetchType.EAGER)
    @ApiModelProperty(notes = "Questionnaire", dataType = "Questionnaire")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Questionnaire questionnaire;

    @ManyToOne(fetch =  FetchType.LAZY)
    @ApiModelProperty(notes = "Form", dataType = "Form")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Form form;

}
